/*
 * Dynamicdns.pro
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Updateip200ResponseAnyOf {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "ip")]
    pub ip: String,
}

impl Updateip200ResponseAnyOf {
    pub fn new(message: String, ip: String) -> Updateip200ResponseAnyOf {
        Updateip200ResponseAnyOf {
            message,
            ip,
        }
    }
}

